export function queryDom() {
  return {
    statusPill: document.querySelector("#statusPill"),
    continentTabs: document.querySelector("#continentTabs"),
    countrySelect: document.querySelector("#countrySelect"),
    regionInput: document.querySelector("#regionInput"),
    searchResults: document.querySelector("#searchResults"),
    visitTypeSelect: document.querySelector("#visitTypeSelect"),
    placeForm: document.querySelector("#placeForm"),
    clearRegionButton: document.querySelector("#clearRegionButton"),
    savedList: document.querySelector("#savedList"),
    continentTitle: document.querySelector("#continentTitle"),
    continentMeta: document.querySelector("#continentMeta"),
    countryTitle: document.querySelector("#countryTitle"),
    countryMeta: document.querySelector("#countryMeta"),
    selectionTitle: document.querySelector("#selectionTitle"),
    selectionMeta: document.querySelector("#selectionMeta"),
    selectionActions: document.querySelector("#selectionActions"),
    tooltip: document.querySelector("#tooltip"),
    continentMap: document.querySelector("#continentMap"),
    countryMap: document.querySelector("#countryMap"),
    countryZoomIn: document.querySelector("#countryZoomIn"),
    countryZoomOut: document.querySelector("#countryZoomOut"),
    metricTotal: document.querySelector('[data-metric="total"]'),
    metricResident: document.querySelector('[data-metric="resident"]'),
    metricTravel: document.querySelector('[data-metric="travel"]'),
    metricTransit: document.querySelector('[data-metric="transit"]'),
    langButtons: [...document.querySelectorAll(".lang-button")],
  };
}
